# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6afb457939c981b3237786947d20258ed23908d91c80eaa61ffb1d53c434684e22a4ca5bf360ae0ff31560d6baa155f4568999f0c3bcf911c7f4550b25ee93e8

test:
  secret_key_base: 678cdee0f08ac69f18f2d80ed7f9294c52a9518ca8249dcf6af590edaf362bf4d48d58d93a4f3513a06d18661b90ebc2ccb42edabf136573ddaa597756db50c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
